# Ejemplo de textos y etiquetas
texts = [
    "Los avances en la inteligencia artificial están transformando el mundo.",
    "La reforestación es vital para combatir el cambio climático.",
    "Los coches eléctricos son cada vez más populares.",
    "La conservación de los océanos es esencial para la biodiversidad.",
    "La realidad virtual ofrece nuevas oportunidades en el entretenimiento y la educación.",
    "La agricultura sostenible puede ayudar a alimentar a la población mundial.",
    "El aprendizaje automático está revolucionando el análisis de datos.",
    "Los paneles solares son una fuente de energía renovable y sostenible.",
    "La programación es una habilidad clave en el mundo tecnológico actual.",
    "Los ecosistemas forestales juegan un papel crucial en el mantenimiento del equilibrio ambiental.",
    "La inteligencia artificial facilita la predicción de patrones en grandes conjuntos de datos.",
    "La deforestación en la Amazonía afecta la biodiversidad global.",
    "El desarrollo de nuevas aplicaciones móviles mejora nuestra vida diaria.",
    "La protección de especies en peligro de extinción es crucial para el ecosistema.",
    "La tecnología blockchain tiene el potencial de revolucionar el sistema financiero.",
    "La energía eólica es una de las fuentes de energía renovable más prometedoras.",
    "Los avances en robótica están creando nuevas oportunidades en la industria manufacturera.",
    "El calentamiento global es uno de los mayores desafíos ambientales de nuestro tiempo.",
    "Las redes neuronales profundas están transformando la visión por computadora.",
    "La conservación del agua es esencial para la sostenibilidad ambiental.",
    "Los dispositivos vestibles están cambiando la forma en que monitoreamos nuestra salud.",
    "El reciclaje ayuda a reducir la contaminación y conservar los recursos naturales.",
    "Los drones están siendo utilizados en diversas aplicaciones, desde la entrega hasta la fotografía aérea.",
    "La agricultura orgánica promueve prácticas sostenibles y saludables en la producción de alimentos.",
    "El desarrollo de software es una carrera en crecimiento en la era digital.",
    "El deshielo de los glaciares es una señal alarmante del cambio climático.",
    "Los avances en medicina son impulsados significativamente por la tecnología.",
    "La preservación de los arrecifes de coral es vital para la vida marina.",
    "La inteligencia artificial está transformando el sector del transporte.",
    "Las áreas protegidas juegan un papel importante en la conservación de la biodiversidad.",
    "La computación cuántica tiene el potencial de cambiar el panorama tecnológico.",
    "El tratamiento de aguas residuales es fundamental para proteger los ecosistemas acuáticos.",
    "Los satélites artificiales desempeñan un papel crucial en la comunicación global.",
    "El compostaje es un método efectivo para gestionar los residuos orgánicos.",
    "El aprendizaje en línea está democratizando el acceso a la educación.",
    "Los humedales proporcionan hábitats críticos para muchas especies.",
    "Los desarrollos en baterías de iones de litio están impulsando la revolución de los vehículos eléctricos.",
    "La polinización por abejas es esencial para la producción de alimentos.",
    "La realidad aumentada ofrece nuevas formas de interacción digital.",
    "El manejo sostenible de los bosques es clave para combatir la deforestación.",
    "Las redes 5G prometen revolucionar la comunicación inalámbrica.",
    "El cultivo de plantas nativas ayuda a mantener el equilibrio ecológico.",
    "La ciberseguridad se ha vuelto crucial en la era digital.",
    "Los parques nacionales contribuyen a la conservación de la vida silvestre.",
    "Los avances en nanotecnología están abriendo nuevas posibilidades en la medicina.",
    "La jardinería urbana apoya la biodiversidad en las ciudades.",
    "El uso de la inteligencia artificial en la medicina está mejorando los diagnósticos.",
    "Los sistemas de riego eficientes son importantes para la agricultura sostenible.",
    "La realidad virtual está transformando la industria del entretenimiento.",
    "Las medidas de conservación son clave para proteger las especies en peligro.",
    "Los vehículos autónomos cambiarán nuestro modo de transporte.",
    "La plantación de árboles es esencial para restaurar los bosques degradados.",
    "La biotecnología está impactando la industria farmacéutica.",
    "Los humedales proporcionan beneficios importantes para el control de inundaciones.",
    "El desarrollo de nuevas tecnologías de almacenamiento de energía es vital para las energías renovables.",
    "La protección de las abejas es crucial para la polinización y la agricultura.",
    "El big data está revolucionando la toma de decisiones en los negocios.",
    "La conservación de ríos y lagos es vital para mantener los ecosistemas acuáticos.",
    "Los avances en la impresión 3D están transformando la fabricación.",
    "La restauración de hábitats naturales es clave para la biodiversidad.",
    "La inteligencia artificial en el sector bancario está mejorando la eficiencia.",
    "El mantenimiento de los arrecifes de coral es crucial para la vida marina.",
    "Los drones están revolucionando la agricultura con técnicas de monitoreo avanzadas.",
    "Las prácticas de pesca sostenible son importantes para la salud de los océanos.",
    "La automatización en la industria manufacturera está aumentando la producción.",
    "Los esfuerzos de reforestación son críticos para combatir el cambio climático.",
    "Los avances en energía solar están promoviendo alternativas energéticas más limpias.",
    "La protección de los manglares es esencial para numerosas especies marinas.",
    "Los sistemas de inteligencia artificial están optimizando el tráfico en las ciudades.",
    "La conservación de la biodiversidad es fundamental para el equilibrio ecológico."

]

labels = [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
          0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]  # 0 para Tecnología, 1 para Naturaleza
